"""
Email Sending Utilities
Handles email functionality using various email services.
"""

import logging
import re
from datetime import datetime
from config.settings import Settings

logger = logging.getLogger(__name__)


class EmailSender:
    """Email sender using Resend API."""

    def __init__(self, api_key=None, from_email=None):
        """Initialize email sender."""
        self.api_key = api_key or Settings.RESEND_API_KEY
        self.from_email = from_email or Settings.EMAIL_FROM

        if not self.api_key:
            raise ValueError("Resend API key not configured")
        if not self.from_email:
            raise ValueError("From email not configured")

    def send(self, to_email, subject, content, content_type="markdown"):
        """
        Send an email.

        Args:
            to_email: Recipient email address
            subject: Email subject line
            content: Email content (markdown or html)
            content_type: "markdown" or "html" (default: markdown)

        Returns:
            True if sent successfully, False otherwise
        """
        try:
            import resend
            resend.api_key = self.api_key

            # Convert markdown to HTML if needed
            if content_type == "markdown":
                html_content = self._create_html_email(content, subject)
            else:
                html_content = content

            params = {
                "from": self.from_email,
                "to": [to_email],
                "subject": subject,
                "html": html_content
            }

            response = resend.Emails.send(params)
            logger.info("Email sent! (ID: %s)", response['id'])
            return True

        except Exception as e:
            logger.error("Email error: %s", e)
            return False

    def _create_html_email(self, markdown_content, title):
        """Create a styled HTML email from markdown content."""
        html_body = self._markdown_to_html(markdown_content)

        return f"""
        <html>
        <head>
            <style>
                body {{
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 20px;
                    background-color: #f5f5f5;
                }}
                .container {{
                    background-color: white;
                    border-radius: 8px;
                    padding: 30px;
                    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
                }}
                h1 {{
                    color: #2c3e50;
                    border-bottom: 3px solid #3498db;
                    padding-bottom: 10px;
                    margin-top: 0;
                }}
                h2 {{
                    color: #34495e;
                    margin-top: 30px;
                    border-left: 4px solid #3498db;
                    padding-left: 15px;
                }}
                h3 {{
                    color: #555;
                    margin-top: 20px;
                }}
                a {{
                    color: #3498db;
                    text-decoration: none;
                }}
                a:hover {{
                    text-decoration: underline;
                }}
                ul {{
                    padding-left: 20px;
                }}
                .footer {{
                    margin-top: 40px;
                    padding-top: 20px;
                    border-top: 2px solid #eee;
                    font-size: 0.9em;
                    color: #777;
                    text-align: center;
                }}
            </style>
        </head>
        <body>
            <div class="container">
                <div>{html_body}</div>
                <div class="footer">
                    <p><strong>Generated by AI Agent</strong></p>
                    <p>Powered by Claude (Anthropic) • {datetime.now().strftime('%B %d, %Y')}</p>
                </div>
            </div>
        </body>
        </html>
        """

    def _markdown_to_html(self, markdown_text):
        """Convert markdown to HTML."""
        html = markdown_text

        # Convert headers (must do in reverse order to avoid conflicts)
        html = re.sub(r'^### (.+)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
        html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
        html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)

        # Convert bold
        html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)

        # Convert links
        html = re.sub(r'\[(.+?)\]\((.+?)\)', r'<a href="\2">\1</a>', html)

        # Convert bullet points
        html = re.sub(r'^\- (.+)$', r'<li>\1</li>', html, flags=re.MULTILINE)
        html = re.sub(r'(<li>.*</li>)', r'<ul>\1</ul>', html, flags=re.DOTALL)

        # Convert line breaks
        html = html.replace('\n\n', '<br><br>')

        return html
